const TermsConditionsPage = () => {
  return (
    <div className="mt-10">
      <h3 className="font-bold text-lg">
        Terms and Conditions
      </h3>

      <span>
       <h3 className="font-bold text-lg">1. Introduction</h3>
       <p className="my-2">1.1.  Welcome to <b>www.tunycemedia.com</b> (hereinafter referred to as "<b>Tunyce Media</b>"), an entertainment streaming platform that allows content creators, advertisers, and users to access and utilize its services. </p>
       <p className="my-2">1.2.  By accessing or using <b>Tunyce Media</b>, you agree to comply with the following terms and conditions. These terms govern your use of the platform, including the uploading, streaming, advertising, and wallet functionalities. </p>
       <p className="my-2">1.3.  These Terms and Conditions of Service apply to the use of the platform (s) and the information, materials, images and/or videos etc. which may be displayed on, incorporated into, underlying, or used to operate the platform(s) including but not limited to databases, text, information, graphics, trade-marks, icons, logos, hyperlinks, sounds, photographs and designs.</p>
       <p className="my-2">1.4.  By accessing and using the Platform(s), you accept and agree to be bound by the terms and provision of this agreement. You shall be subject to any posted guidelines and/or rules applicable to such platform(s). You shall be solely responsible for reviewing these Terms from time to time. Any participation in the platform(s) will constitute acceptance of this agreement. If you do not agree to abide by the above, please do not use the Platform(s).</p>
       <p className="my-2">1.5.  Please note that Tunyce Media reserves the right to change, modify, add or remove these Terms and Conditions, or any part thereof, at any time. These changes shall be effective immediately they are posted on the Platforms(s) and no other advance notice shall be required or provided. Users of the Platform(s) are advised to regularly check on these Terms and Conditions for updates. Continued use of the Platform(s) after changes have been made constitutes acceptance of those changes. </p>
       <p className="my-2">1.6.  These terms and conditions shall apply to each and all the products and services, whenever applied for or provided to the User, and in the event of any conflict and/or inconsistency between the  terms and conditions of service of a specific product or service, such conflict or inconsistency shall, in the absence of any express agreement to the contrary be resolved in a manner most favorable to Tunyce Media and to the exercise of Tuncyce Media’s rights and options with respect to any matter and issue to which the inconsistency relates.  </p>
       <p className="my-2">1.7.  Tunyce Media shall reserve the right to accept, to refuse and/or execute any services, and to cancel services in whole or in part in their absolute discretion without giving any reasons thereof. </p>
       <p className="my-2">1.8.  These terms and conditions of service shall, together with the Privacy Policy govern the legal relationship between Tunyce Media and its Users.</p>
       <p className="my-2">1.9.  TAKE NOTE THAT THESE TERMS AND CONDITIONS CONTAIN PROVISIONS THAT DISCLAIM, LIMIT AND EXCLUDE THE LIABILITY OF TUNYCE MEDIA TO YOU AND THAT INDEMNIFY TUNYCE MEDIA AGAINST CLAIMS AND DAMAGES THAT IT OR THIRD PARTIES MAY SUFFER AS A RESULT OF YOUR CONDUCT.</p>
       Please read these terms carefully, as they form a legally binding agreement between you and <b>Tunyce Media</b>.
       
       <h3 className="font-bold text-lg">2. Definition</h3> 
       <p className="my-2">2.1  In these terms and conditions of service, unless the context otherwise requires, the following terms shall have the following meanings:   </p>
       <p className="my-2">2.1.1.  "<b>Tunyce Media</b>," "we," "us," or "our" refer to the legal entity, operators and administrators of the www.tunycemedia.com web platform.</p>
       <p className="my-2">2.1.2.  "<b>Advertisers</b>" refer to individuals or entities who book advertising spots and display advertisements on the platform.</p>
       <p className="my-2">2.1.3.  "<b>Content Creators</b>" refer to individuals or entities who upload entertainment content, such as Deejays and other media creators, to the platform.</p>
       <p className="my-2">2.1.4.  "<b>Display Medium Administrators</b>" are individuals or entities responsible for managing display mediums (e.g., public transit systems, restaurants, hotels) where Tunyce content is streamed.</p>
       <p className="my-2">2.1.5.  "<b>Users</b>' refer to all individuals who access or use Tunyce Media, including Content Creators, Advertisers, and Display Medium Administrators.</p>
       <p className="my-2">2.1.6.  "<b>Wallet</b>" refers to the custom payment system on Tunyce Media that allows users to hold funds, pay for content subscriptions, and all transactional functions on the platform.</p>
       <p className="my-2">2.2.  Any reference to the words used in these terms and conditions of service shall be regarded as follows:</p>
       <p className="my-2">2.2.1.  Any clause headings inserted into these terms and conditions of service are to facilitate reference and shall not be referred to or relied upon in the interpretation of the terms and conditions of service.</p>
       <p className="my-2">2.2.2.  Any word and or expression defined in any other part of these terms and conditions of service shall bear the meaning of such words or expressions as assigned.</p>
       <p className="my-2">2.2.3.  Where the context so admits, the singular shall include the plural and words in the masculine gender shall include the feminine gender and/or neuter gender and vice-versa.</p>
       <p className="my-2">2.2.4.  Where, any provision of these terms and conditions of service conflict with any law, then to the limited extent of such conflict, such provision shall not be in connection with these terms of service and shall not affect its enforceability.</p>
       <p className="my-2">2.2.5.  The terms "you", and "your" and "user" shall mean any person who accesses or uses the platform(s).</p>

       <h3 className="font-bold text-lg">3.  Use of the Webplatform</h3> 
       <h4>3.1.  User Accounts </h4>
       <p className="my-2">3.1.1.  The user is responsible for maintaining the confidentiality of their account login credentials, including their username and password. Any activities that occur under the user's account shall be deemed as the user's actions and are solely the user's responsibility. The user must notify Tunyce Media immediately of any unauthorized use or suspected security breach of their account.</p>
       <p className="my-2">3.1.2.  Any person that uses the Platform(s) shall have attained the legal age of Eighteen (18) years (or the age of legal majority in your jurisdiction) or in the alternative, the user shall access the Platform(s) under the strict supervision of a parent or legal guardian.</p>
       <p className="my-2">3.1.3.  Some services and/or products available on the Platform(s) may require you to register and/or subscribe in order to obtain them. For purposes of registration, Tunyce Media requires certain personal information such as your name, email address and mobile number. Should you choose to register or subscribe for any 	such services or related features, you agree to provide accurate and current information about yourself, and to promptly update such information if there are any changes. Your failure to maintain accurate, complete, and up-to-date information may result in your inability to access or use the Services available on the Platform(s).  </p>
       <p className="my-2">3.1.4.  Unless otherwise permitted by Tunyce Media in writing, you may only possess one Account.  </p>
       <p className="my-2">3.1.5.  You are responsible for maintaining the confidentiality of your account credentials and must not share them with others. Any activity on your account is your responsibility whether authorized by you or not.</p>
       <p className="my-2">3.1.6.  Any person who is not in agreement to all the terms and conditions of service of this agreement or be unable to comply, fulfil and/or adhere with these terms and conditions of service, shall immediately cease/terminate use of the platform(s). </p> 
       <p className="my-2">3.1.7.  Tunyce Media reserves the right to suspend or terminate a user's account, in its sole discretion, for various reasons including but not limited to: (a) violation of these Terms and Conditions of Service or any applicable laws and regulations; (b) engaging in fraudulent, illegal, or unauthorized activities; (c) misuse, abuse, or unauthorized access of the services; (d) conduct that may cause harm to Tunyce Media, other users, or third parties; (e) failure to provide accurate and up-to-date information; or (f) any other actions that Tunyce Media deems detrimental to its operations or reputation. In the event a user wishes to terminate their account with Tunyce Media, they must contact the customer support team for assistance. Upon account termination, the user's access to the services will be disabled, and any outstanding obligations or liabilities shall continue to apply.</p>

       <h3 className="font-bold text-lg">4.  Acceptable Usage</h3>
       <p className="my-2">4.1.  By accessing and using the services provided by Tunyce Media, Users acknowledges and accepts full responsibility for their actions and compliance with these Terms and Conditions of Service. The user agrees to use the services only for lawful purposes and in accordance with all applicable laws, regulations, and codes of conduct.</p>
       <p className="my-2">4.2.  Users agrees to provide accurate and current information when registering or subscribing for any services offered by Tunyce Media. It is the user's responsibility to promptly update their information if any changes occur. Tunyce Media shall not be held liable for any consequences arising from the user's failure to provide accurate and up-to-date information.</p>
       <p className="my-2">4.3.  Users acknowledge and understand that Tunyce Media acts as a conduit for the provision of information and content from the various third parties regarding the Services and Products offered/displayed on the Platform(s).  </p>
       <p className="my-2">4.4.  Users acknowledge that Tunyce Media shall not be responsible or liable for any content transmitted and that full responsibility for content shall rest on the User 	as well as the third party providers. </p>
       <p className="my-2">4.5.  It shall be the sole responsibility of Users to familiarize themselves with all applicable laws, regulations and codes of conduct to which they may be subject and to ensure compliance therewith. </p>
       <p className="my-2">4.6.  Users who wish to use or link to the Platform(s) for any purpose, or in any way, not expressly permitted in these Terms and Conditions of Service, may only do so with the express prior written permission of Tunyce Media.  </p>
       <p className="my-2">4.7.  Tunyce Media, at any time and for any reason, reserves the right to revoke your access or use of the Platform(s) or the Content without giving you any notice or informing you of this.</p>
       <p className="my-2">4.8.  Users shall not allow persons under the age of Eighteen (18) years to use their accounts to receive the Services from third party providers unless in accordance with the terms herein. Users shall also not transfer their Account to any other person or entity. </p>
       <p className="my-2">4.9.  Users shall neither do, nor omit to do, anything that would result, directly or indirectly, in any breach by Tunyce Mediaor by the User of any requirement or provision of any applicable legislation, regulations, code of conduct or failing which Tunyce Media shall be entitled to immediately suspend or terminate the provision of Services to the User and the User shall have no claim of any nature against Tunyce Media (including claims for re-imbursement, refund, compensation or damages).  </p>
       <p className="my-2">4.10.  Users hereby indemnify Tunyce Media against any fine imposed on Tunyce Media or any damages suffered by TUNYCE MEDIA as a result of any act or omission of a User that amounts to a breach of any law or code of conduct to which TUNYCE MEDIA may be subject. Upon notification of any such fine or damages, Users agree to 	immediately pay the amount of such fine or damages to TUNYCE MEDIA. Any amount not paid to TUNYCE MEDIA within twenty four (24) hours of notification thereof shall accrue an interest. Users may not use, or knowingly allow others to use, the Services for any purpose that may bring TUNYCE MEDIA’S name into disrepute, or for any purpose that, in TUNYCE MEDIA’S sole and absolute discretion, is improper, immoral or undesirable.</p>
       <p className="my-2">4.11.  Users may not use the Platform(s) to send messages without reasonable cause or for the purpose of causing annoyance, inconvenience or distress to any person. </p>
       <p className="my-2">4.12.  Users acknowledge and agree that all messages, reviews and posts made on the Platform(s) shall be stored and can be audited and reviewed by TUNYCE MEDIA or any other person acting on behalf of TUNYCE MEDIA at any time to ensure compliance with these terms and conditions of service and any applicable law, regulations or code of conduct.</p>

       <h3 className="font-bold text-lg">5.  Intellectual Property Rights</h3>
       <p className="my-2">5.1.  Content Creators retain all intellectual property rights to the content they upload on Tunyce Media. By uploading content, Content Creators grant Tunyce Media a non-exclusive, worldwide, royalty-free license to use, reproduce, distribute, and display the content for the purposes of streaming and promoting the platform.</p>
       <p className="my-2">5.2.  Advertisers retain all intellectual property rights to their advertisements. By booking advertising spots, Advertisers grant Tunyce Media a license to display their advertisements on the platform.</p>
       <p className="my-2">5.3.  All content and materials on Tunyce Media, including but not limited to the platform's design, logos, graphics, and software, are the property of Tunyce Media and protected by copyright and other intellectual property laws.</p>
       
       <h3 className="font-bold text-lg">6.  Restrictions</h3>
       <p className="my-2">6.1.  Any content provided on the Platform(s) is solely for informational purposes. The products and services represented and conveyed on the Platform(s) are those of Third Party Providers and are note made by the Platform(s).  </p>
       <p className="my-2">6.2.  The opinions, offers and submissions communicated on the Platform(s) are those of the individuals posting such content and do not represent the opinions of the Platform(s), if any.</p>
       <p className="my-2">6.3.  Every user of the Platform shall be solely responsible for keeping passwords and other account identifiers safe and secure. The account owner is entirely responsible for all activities that occur under such password or account. Furthermore, you must notify TUNYCE MEDIA of any unauthorized use of your password or account. The Platform shall not be responsible or liable, directly or indirectly, in any way for any loss or damage of any kind incurred as a result of, or in connection with, your failure to comply with this section.</p>
       
       <h3 className="font-bold text-lg">7.  Text Messaging and Telephone Calls</h3>
       <p className="my-2">7.1.  Upon registration/subscription, you agree that TUNYCE MEDIA may contact you via telephone, email or text messages at any of the phone numbers and/or email addresses provided by you or on your behalf in connection with a TUNYCE MEDIA Account, including for marketing purposes.</p>
       <p className="my-2">7.2.  You can subsequently opt out of receiving such promotional e-mails and text messages from TUNYCE MEDIA by clicking on the link at the bottom of any promotional e-mail or texting the word “STOP” to the number provided in the text message. </p>
       <p className="my-2">7.3.  Anything submitted to the Platform and/or provided to TUNYCE MEDIA, including but not limited to questions, reviews, comments and suggestions will become the Platform’s sole and exclusive property and shall not be returned to you. Additionally, any comments and/or reviews made on the platform grants TUNYCE MEDIA the right to use the name that you submit, in connection with such review, comment or other content. You shall not use a false e-mail address, pretend to be someone other than yourself or otherwise mislead TUNYCE MEDIA or third parties as to the origin of any Submissions. TUNYCE MEDIA may, but shall not be obligated to, remove or edit any submissions. </p>
       <p className="my-2">7.4.  You may not: (i) remove any copyright, trademark or other proprietary notices from any portion of the Services; (ii) reproduce, modify, prepare derivative works based upon, distribute, license, lease, sell, resell, transfer, publicly display, publicly perform, transmit, stream, broadcast or otherwise exploit the Services except as expressly permitted by TUNYCE MEDIA; (iii) decompile, reverse engineer or disassemble the Services except as may be permitted by applicable law; (iv) link to, mirror or frame any portion of the Services; (v) cause or launch any programs or scripts for the purpose of scraping, indexing, surveying, or otherwise data mining any portion of the Services or unduly burdening or hindering the operation and/or functionality of any aspect of the Services; or (vi) attempt to gain unauthorized access to or impair any aspect of the Services or its related systems or networks.</p>
       
       <h3 className="font-bold text-lg">8.  Access Networks and Device</h3>
       <p className="my-2">8.1.  You are responsible for obtaining the data network access necessary to use the Platform(s) and the Services therein unless Tuncye Media at its discretion decides to provide the data network. Your mobile network's data and messaging rates and fees may apply if you access or use the Services from your device. You are responsible for acquiring and updating compatible hardware or devices necessary to access and use the Services and Applications and any updates thereto. TUNYCE MEDIA does not guarantee that the Services, or any portion thereof, will function on any particular hardware or devices. In addition, the Services may be subject to malfunctions and delays inherent in the use of the Internet and electronic communications.</p>
       
       <h3 className="font-bold text-lg">9.  Data Privacy</h3>
       <p className="my-2">9.1.  Tunyce Media collects and processes personal data in accordance with its Privacy Policy. By using the platform, you consent to the collection and use of your data as described in the Privacy Policy.</p>
       
       <h3 className="font-bold text-lg">10.  Content Guidelines</h3>
       <p className="my-2">10.1.  Users are strictly prohibited from uploading or displaying content that is illegal, infringes intellectual property rights, contains explicit material, promotes hate speech, or violates any applicable laws or regulations.</p>
       <p className="my-2">10.2.  Tunyce Media may monitor and moderate content to ensure compliance with these terms and conditions. However, Tunyce Media does not guarantee the accuracy, quality, or legality of user-uploaded content.</p>
       
       <h3 className="font-bold text-lg">11.  Advertisements</h3>
       <p className="my-2">11.1.  Advertisers can book advertising spots and pay through their wallets, subject to availability of slots and compliance with these terms.</p>
       <p className="my-2">11.2.  Advertisers may schedule adverts to accompany entertainment content on Tunyce Media. By scheduling ads, advertisers confirm they have the authority to promote the advertised products or services</p>
       <p className="my-2">11.3.  Tunyce Media reserves the right to approve or reject any advertisement based on content guidelines and suitability.</p>
       <p className="my-2">11.4.  Advertisers can book various ad spots and formats available on the platform, subject to availability and approval by Tunyce Media.</p>
       <p className="my-2">11.5.  All payments made for advertising spots or content subscriptions will be processed through the Wallet feature on the Webplatform. </p>
       <p className="my-2">11.6.  Tunyce Media reserves the right to adjust advertising rates at its discretion without prior notice.</p>
       
       <h3 className="font-bold text-lg">12.  Wallet Usage</h3>
       <p className="my-2">12.1.  Tunyce provides a custom wallet feature for Advertising Medium Administrators to pay for content subscriptions directly to Content Creators. Content Creators will receive subscription payments directly into their wallets. Advertisers can pay for booked advertising spots directly through their wallet.</p>
       <p className="my-2">12.2.  Users can fund their wallets through approved payment methods to pay for content subscriptions and advertising bookings.</p>
       <p className="my-2">12.3.  Users are responsible for maintaining the security of their wallets and must not share their account details with others. Tunyce will handle all financial transactions securely and in accordance with applicable </p>
       
       <h3 className="font-bold text-lg">13.  Payments and Subscriptions</h3>
       <p className="my-2">13.1. Subscription fees for accessing content and advertising fees are determined by Tunyce and may be subject to change.</p>
       <p className="my-2">13.2. Payments made through the custom wallet must be accurate, and any payment disputes should be promptly addressed through Tunyce's support system.</p>
       <p className="my-2">13.3. Users who subscribe to Content Creators' content agree to pay the designated subscription fees.</p>
       <p className="my-2">13.4. Content Creators will receive subscription payments directly into their wallets on Tunyce Media.</p>
       <p className="my-2">13.5  Content creators will start getting subscriptions once they have 5 or more uploads</p>
       <p className="my-2">13.6. Tunyce Media may deduct transaction fees or commissions as agreed upon from subscription payments to Content Creators.</p>
       
       <h3 className="font-bold text-lg">14. Limitation of Liability, Warranties and Indemnities</h3>
       <p className="my-2">14.1.  Tunyce Media shall not be liable for any direct, indirect, incidental, or consequential damages arising from the use or inability to use the platform.</p>
       <p className="my-2">14.2.  Users agree to indemnify and hold Tunyce Media harmless from any claims, damages, fines, losses, risk or liabilities arising from their use of the platform.</p>
       <p className="my-2">14.3.  TUNYCE MEDIA provides the services, information, content, and materials on the platform on an "as is" and "as available" basis, without any warranties or guarantees of any kind, whether express or implied. TUNYCE MEDIA disclaims all warranties, including but not limited to the accuracy, reliability, suitability, or completeness of the information, content, or services offered on the platform. </p>
       <p className="my-2">14.4.  TUNYCE MEDIA shall not be liable for any damage, loss or liability of whatever nature arising from the use or inability to use the services or any other content provided.</p>
       <p className="my-2">14.5.  Further, TUNYCE MEDIA makes no representations or warranties, implied or otherwise, amongst others, that the contents available from the Platform(s) are free from errors or omissions or that the products and services will be 100% error free and uninterrupted.</p>
       <p className="my-2">14.6.  These terms and conditions of service together with any other contractual documents expressly referenced in these terms and conditions of service contain all of the terms of agreement between the User and TUNYCE MEDIA.</p>
       <p className="my-2">14.7.  The products and services supplied are on an "as is" basis and are not supplied to meet the User's individual requirements. To the fullest extent permitted by law, TUNYCE MEDIA disclaims all representations and warranties relating to the Services (whether express, implied and statutory, including but not limited to the warranties of merchantability and fitness for a particular purpose). It is the sole responsibility of the User to satisfy itself prior to entering into this agreement with TUNYCE MEDIA that the product and services will meet the User's individual needs and requirements.</p>
       <p className="my-2">14.8.  Users shall not hold TUNYCE MEDIA against any reasonable damages, awards, penalties or legal costs claimed or imposed by any party as a result of any commission or omission by the User that constitutes a breach of any legislation, regulations, code of conduct or network provider codes or practice or acceptable usage policies.</p>
       <p className="my-2">14.9.  Users shall indemnify TUNYCE MEDIA and hold them unaccountable against any reasonable claims, actions or damages from any party as a result of the fraudulent or unauthorized use of the User's Username and password or loss thereof.</p>
       <p className="my-2">14.10.  Without derogating from the foregoing, TUNYCE MEDIA shall not be liable for any damages whatsoever, including but not limited to any direct, indirect, special, consequential, punitive or incidental damages, or damages for loss of use, profits, data or other intangibles, or the cost of procurement of substitute goods and services, arising out of or related to the use, inability to use or unauthorized use of the services, whether such damages arise in contract, under statute, in equity, at law or otherwise.</p>
       <p className="my-2">14.11.  Notwithstanding the foregoing provisions, in the event that a User has a valid claim against TUNYCE MEDIA arising from any services provided under these terms and conditions of service then the User's claim shall be limited to payment of an amount equal to the amount paid for the products or services that are the subject of the claim in the month prior to any such claim arising.</p>
       
       <h3 className="font-bold text-lg">15.  General</h3>
       <p className="my-2">15.1.  The failure of either party to exercise in any respect any right provided for herein will not be deemed a waiver of any further rights hereunder. If any provision of these terms and conditions of service is found to be unenforceable or invalid, such term(s) or condition(s) shall be severable from the remaining terms and conditions of service. The remaining terms and conditions of service shall not be affected by such unenforceability or invalidity and shall remain enforceable and applicable.</p>
       
       <h3 className="font-bold text-lg">16.  Suspension and Termination </h3>
       <p className="my-2">16.1.  TUNYCE MEDIA may suspend (indefinitely or for such period as it may consider appropriate) or terminate any services at any time by giving sufficient notice to the User and stating its reason(s) for the suspension on termination of the service and, in any circumstances which TUNYCE MEDIA deems appropriate, the means by which the User can avoid such suspension or termination provided that nothing herein shall prejudice or affect any right(s) of TUNYCE MEDIA to suspend or terminate any service.</p>
       <p className="my-2">16.2.  In addition to any other legal or equitable remedies, we may, without prior notice to you, immediately terminate the Terms and Conditions or revoke any or all of your rights granted under the Terms and Conditions. Upon the termination of the Terms and Conditions, we shall, in addition to any other legal or equitable remedies, immediately revoke the password and account identification issued to you and deny your access to and use of the Platform in whole or in part. </p>
       <p className="my-2">16.3.  Any termination of the Terms and Conditions shall not affect the respective rights and obligations (including without limitation payment obligations) of the parties arising before the date of termination. You furthermore agree that the Platform shall not be liable to you or to any other person as a result of any such suspension or termination. If you are dissatisfied with the Platform or with any terms, conditions, rules, policies, guidelines or practices in operating the Platform, your sole and exclusive remedy is to discontinue using the Platform. </p>
       
       <h3 className="font-bold text-lg">17.  Modification of Terms</h3>
       <p className="my-2">17.1.  Tunyce Media may modify these terms and conditions at any time. The updated terms will be posted on the webplatform, and continued use of the platform after such modifications constitutes acceptance of the updated terms.</p>
       
       <h3 className="font-bold text-lg">18.  Force Majeure </h3>
       <p className="my-2">18.1.  Neither party will be liable for any delay in the performance of or any failure to perform any of its obligations under this Agreement that is caused by any event which is beyond its reasonable control including, without limitation, strikes, work stoppages, pandemics, accidents, acts of war or terrorism, civil or military disturbances, natural catastrophes or acts of God, and interruptions, loss or malfunctions of utilities, communications or computer (software and hardware) services. </p>
       
       <h3 className="font-bold text-lg">19.  Governing Law and Jurisdiction</h3>
       <p className="my-2">19.1.  These terms and conditions shall be governed by the laws of Kenya.</p>
       <p className="my-2">19.2.  Any disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Kenya.</p>
       
        <h3 className="font-bold text-lg">20.  Severability</h3>
        <p className="my-2">20.1.  If any provision of these Terms and Conditions is found to be invalid or unenforceable, the remaining provisions shall remain in full force and effect.</p>

       <h3 className="font-bold text-lg">21.  Entire Agreement</h3>
       <p className="my-2">21.1.  These Terms constitute the entire agreement between you and Tunyce Media regarding your use of the Web platform, superseding any prior agreements or communications.</p>
       
       <h3 className="font-bold text-lg">By using www.tunycemedia.com, you acknowledge that you have read, understood, and agree to these Terms and Conditions. If you have any questions or concerns, please contact us at info@tunycemedia.com</h3>
       
      </span>
    </div>
  )
}
export default TermsConditionsPage
